<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.farmafene.j2ee</groupId>
	<artifactId>tx-utils</artifactId>
	<version>1.0.0-m0</version>
	<name>${project.groupId}:${project.artifactId}</name>
	<description><![CDATA[JTA utils for Spring]]></description>
	<url><![CDATA[https://github.com/venanciolm/tx-utils]]></url>
	<properties>
		<java.version>17</java.version>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<project.scm.id>GITHUB.ID</project.scm.id>
		<!-- -->
		<maven-toolchains-plugin>3.0.0</maven-toolchains-plugin>
		<maven-compliler-plugin>2.3.2</maven-compliler-plugin>
		<maven-scm-plugin>1.9.4</maven-scm-plugin>
		<maven-bundle-plugin>6.0.0</maven-bundle-plugin>
		<maven-javadoc-plugin>2.10.3</maven-javadoc-plugin>
		<maven-source-plugin>2.4</maven-source-plugin>
		<maven-release-plugin>2.5.3</maven-release-plugin>
		<maven-deploy-plugin>2.8.2</maven-deploy-plugin>
		<central-publishing-maven-plugin>0.8.0</central-publishing-maven-plugin>
		<maven-gpg-plugin>3.2.8</maven-gpg-plugin>
		<!-- -->
		<!-- -->
		<!-- Versions -->
		<!-- -->
		<jakarta.transaction-api.VERSION>2.0.1</jakarta.transaction-api.VERSION>
		<jakarta.resource-api.VERSION>2.1.0</jakarta.resource-api.VERSION>
		<jakarta.jms-api.VERSION>3.1.0</jakarta.jms-api.VERSION>
		<hibernate-core.VERSION>6.6.22.Final</hibernate-core.VERSION>
		<org.springframework.VERSION>6.2.9</org.springframework.VERSION>
		<org.slf4j.VERSION>2.0.17</org.slf4j.VERSION>
		<log4j.VERSION>2.24.3</log4j.VERSION>
	</properties>
	<scm>
		<tag>1.0.0-m0</tag>
		<url><![CDATA[https://github.com/venanciolm/tx-utils]]></url>
		<connection><![CDATA[scm:git:https://github.com/venanciolm/tx-utils.git]]></connection>
		<developerConnection><![CDATA[scm:git:https://github.com/venanciolm/tx-utils.git]]></developerConnection>
	</scm>
	<distributionManagement>
		<repository>
			<id>CENTRAL.GOOGLE.ID</id>
			<url><![CDATA[https://repo1.maven.org/maven2]]></url>
		</repository>
		<snapshotRepository>
			<id>CENTRAL.GOOGLE.ID</id>
			<url><![CDATA[https://central.sonatype.com/repository/maven-snapshots/]]></url>
		</snapshotRepository>
	</distributionManagement>
	<repositories>
		<repository>
			<id>central-portal-snapshots</id>
			<url>https://central.sonatype.com/repository/maven-snapshots/</url>
			<releases>
				<enabled>false</enabled>
			</releases>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
	</repositories>
	<licenses>
		<license>
			<name>The Apache License, Version 2.0</name>
			<url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
		</license>
	</licenses>
	<developers>
		<developer>
			<name>Venancio López Martínez</name>
			<email>venanciolm -at- gmail.com</email>
			<organization>farmafene</organization>
			<organizationUrl>http://farmafene.com</organizationUrl>
		</developer>
	</developers>
	<dependencies>
		<dependency>
			<groupId>jakarta.transaction</groupId>
			<artifactId>jakarta.transaction-api</artifactId>
			<version>${jakarta.transaction-api.VERSION}</version>
		</dependency>
		<dependency>
			<groupId>jakarta.resource</groupId>
			<artifactId>jakarta.resource-api</artifactId>
			<version>${jakarta.resource-api.VERSION}</version>
		</dependency>
		<dependency>
			<groupId>jakarta.jms</groupId>
			<artifactId>jakarta.jms-api</artifactId>
			<version>${jakarta.jms-api.VERSION}</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>${org.slf4j.VERSION}</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>jcl-over-slf4j</artifactId>
			<version>${org.slf4j.VERSION}</version>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.hibernate.orm</groupId>
			<artifactId>hibernate-core</artifactId>
			<version>${hibernate-core.VERSION}</version>
			<scope>provided</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-beans</artifactId>
			<version>${org.springframework.VERSION}</version>
			<scope>provided</scope>
			<exclusions>
				<exclusion>
					<groupId>org.springframework</groupId>
					<artifactId>spring-jcl</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-slf4j2-impl</artifactId>
			<version>${log4j.VERSION}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-core</artifactId>
			<version>${log4j.VERSION}</version>
			<scope>test</scope>
		</dependency>
	</dependencies>
	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-toolchains-plugin</artifactId>
					<version>${maven-toolchains-plugin}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>${maven-compliler-plugin}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-scm-plugin</artifactId>
					<version>${maven-scm-plugin}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-source-plugin</artifactId>
					<version>${maven-source-plugin}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-javadoc-plugin</artifactId>
					<version>${maven-javadoc-plugin}</version>
				</plugin>
				<plugin>
					<groupId>org.sonatype.central</groupId>
					<artifactId>central-publishing-maven-plugin</artifactId>
					<version>${central-publishing-maven-plugin}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-gpg-plugin</artifactId>
					<version>${maven-gpg-plugin}</version>
				</plugin>
			</plugins>
		</pluginManagement>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-toolchains-plugin</artifactId>
				<executions>
					<execution>
						<id>default</id>
						<goals>
							<goal>toolchain</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<toolchains>
						<jdk>
							<version>${java.version}</version>
						</jdk>
					</toolchains>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-scm-plugin</artifactId>
			</plugin>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>${java.version}</source>
					<target>${java.version}</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-javadoc-plugin</artifactId>
				<configuration>
					<source>${java.version}</source>
					<show>private</show>
					<failOnError>false</failOnError>
					<additionalparam>-Xdoclint:none</additionalparam>
				</configuration>
				<executions>
					<execution>
						<id>attach-javadoc</id>
						<goals>
							<goal>jar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-source-plugin</artifactId>
				<configuration>
					<outputDirectory>${basedir}/target</outputDirectory>
					<attach>true</attach>
					<forceCreation>false</forceCreation>
					<includePom>true</includePom>
				</configuration>
				<executions>
					<execution>
						<id>attach-sources</id>
						<goals>
							<goal>jar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-release-plugin</artifactId>
				<configuration>
					<tagNameFormat>@{project.version}</tagNameFormat>
					<detail>true</detail>
					<preparationGoals>install</preparationGoals>
					<autoVersionSubmodules>true</autoVersionSubmodules>
					<arguments>-DskipTests</arguments>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.sonatype.central</groupId>
				<artifactId>central-publishing-maven-plugin</artifactId>
				<extensions>true</extensions>
				<configuration>
					<autoPublish>true</autoPublish>
					<waitUntil>uploaded</waitUntil>
					<skipPublishing>false</skipPublishing>
					<deploymentName>${project.artifactId}@${project.version}</deploymentName>
					<publishingServerId>CENTRAL.GOOGLE.ID</publishingServerId>
				</configuration>
			</plugin>
		</plugins>
	</build>
	<profiles>
		<profile>
			<!-- @See
			https://www.sonatype.com/blog/2010/01/how-to-generate-pgp-signatures-with-maven
			 -->
			<id>release-sign-artifacts</id>
			<activation>
				<property>
					<name>performRelease</name>
					<value>true</value>
				</property>
			</activation>
			<build>
				<plugins>
					<plugin>
						<!--<server>-->
						<!--	<id>gpg.passphrase</id>-->
						<!--	<passphrase> ... Clara o cifrada
						...</passphrase>-->
						<!--</server>-->
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-gpg-plugin</artifactId>
						<executions>
							<execution>
								<id>sign-artifacts</id>
								<phase>verify</phase>
								<goals>
									<goal>sign</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>